"""user_model

Revision ID: 0abd09a9803a
Revises: cb1fff64a269
Create Date: 2025-08-06 20:57:17.436177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0abd09a9803a'
down_revision: Union[str, Sequence[str], None] = 'cb1fff64a269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enrollment', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('user', sa.Column('is_subscibed', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('subscribed_until', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('user', 'premium_until')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('premium_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('user', 'subscribed_until')
    op.drop_column('user', 'is_subscibed')
    op.alter_column('enrollment', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
