"""metrics table

Revision ID: 12d47ec1221c
Revises: a8978792fa54
Create Date: 2025-08-28 13:34:51.026188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d47ec1221c'
down_revision: Union[str, Sequence[str], None] = 'a8978792fa54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('total_courses', sa.Integer(), nullable=False),
    sa.Column('monthly_revenue', sa.Integer(), nullable=False),
    sa.Column('change_users', sa.Integer(), nullable=False),
    sa.Column('change_courses', sa.Integer(), nullable=False),
    sa.Column('change_revenue', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.drop_table('metrics')
    # ### end Alembic commands ###
