"""user_role

Revision ID: 16d87169142f
Revises: 141cfc063c06
Create Date: 2025-08-07 20:51:03.835772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16d87169142f'
down_revision: Union[str, Sequence[str], None] = '141cfc063c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('FREE', 'PREMIUM', name='userrole'),
               type_=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('FREE', 'PREMIUM', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###
