"""metrics table - gR

Revision ID: 2ac875a54653
Revises: 12d47ec1221c
Create Date: 2025-08-28 14:52:06.790865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac875a54653'
down_revision: Union[str, Sequence[str], None] = '12d47ec1221c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('total_subscribers', sa.Integer(), nullable=False))
    op.add_column('metrics', sa.Column('change_subscribers', sa.Integer(), nullable=False))
    op.add_column('metrics', sa.Column('growth_rate', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metrics', 'growth_rate')
    op.drop_column('metrics', 'change_subscribers')
    op.drop_column('metrics', 'total_subscribers')
    # ### end Alembic commands ###
