"""trans_modifs

Revision ID: 3b4450aaddd3
Revises: 5c8f5e917763
Create Date: 2025-07-22 14:36:53.471980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4450aaddd3'
down_revision: Union[str, Sequence[str], None] = '5c8f5e917763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('premium_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'premium_until')
    # ### end Alembic commands ###
