"""trans_status modif

Revision ID: 5c8f5e917763
Revises: 9ce44c717d5a
Create Date: 2025-07-13 03:51:08.360551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5c8f5e917763'
down_revision: Union[str, Sequence[str], None] = '9ce44c717d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    transstatus = postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', name='transstatus')
    transstatus.create(op.get_bind())
    
    op.alter_column('transaction', 'status',
               existing_type=sa.VARCHAR(),
               type_=transstatus,
               existing_nullable=False,
               postgresql_using='status::text::transstatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    transstatus = postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', name='transstatus')
    op.alter_column('transaction', 'status',
               existing_type=transstatus,
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='status::text')
    # ### end Alembic commands ###
