"""Metrics Enrollment rel

Revision ID: 677db9232840
Revises: f9fb57bde513
Create Date: 2025-08-30 13:13:57.984386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '677db9232840'
down_revision: Union[str, Sequence[str], None] = 'f9fb57bde513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('enrollment_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'metrics', 'enrollment', ['enrollment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'metrics', type_='foreignkey')
    op.drop_column('metrics', 'enrollment_id')
    # ### end Alembic commands ###
