"""User, Course, Metrics - modif

Revision ID: 8b4f8e2d80d5
Revises: 2ac875a54653
Create Date: 2025-08-28 16:24:00.970086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4f8e2d80d5'
down_revision: Union[str, Sequence[str], None] = '2ac875a54653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_course_is_active'), 'course', ['is_active'], unique=False)
    op.drop_constraint(op.f('transaction_transaction_id_key'), 'transaction', type_='unique')
    op.create_index(op.f('ix_transaction_transaction_id'), 'transaction', ['transaction_id'], unique=True)
    op.add_column('user', sa.Column('is_subscribed', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_user_is_subscribed'), 'user', ['is_subscribed'], unique=False)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.drop_column('user', 'is_subscibed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_subscibed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_is_subscribed'), table_name='user')
    op.drop_column('user', 'is_subscribed')
    op.drop_index(op.f('ix_transaction_transaction_id'), table_name='transaction')
    op.create_unique_constraint(op.f('transaction_transaction_id_key'), 'transaction', ['transaction_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_course_is_active'), table_name='course')
    # ### end Alembic commands ###
