"""Announcement_preview

Revision ID: a39f289753b6
Revises: 0c64885d0989
Create Date: 2025-08-23 10:20:14.624436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39f289753b6'
down_revision: Union[str, Sequence[str], None] = '0c64885d0989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcement', sa.Column('preview', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcement', 'preview')
    # ### end Alembic commands ###
