"""Transaction attr add

Revision ID: a8978792fa54
Revises: 36143367e898
Create Date: 2025-08-28 09:01:42.188318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8978792fa54'
down_revision: Union[str, Sequence[str], None] = '36143367e898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('transaction_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'transaction', ['transaction_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='unique')
    op.drop_column('transaction', 'transaction_id')
    # ### end Alembic commands ###
