"""refresh token

Revision ID: f030eca78179
Revises: 16d87169142f
Create Date: 2025-08-11 16:27:29.241953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f030eca78179'
down_revision: Union[str, Sequence[str], None] = '16d87169142f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refreshtokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refreshtokens_expires_at'), 'refreshtokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refreshtokens_id'), 'refreshtokens', ['id'], unique=False)
    op.create_index(op.f('ix_refreshtokens_token_hash'), 'refreshtokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refreshtokens_user_id'), 'refreshtokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refreshtokens_user_id'), table_name='refreshtokens')
    op.drop_index(op.f('ix_refreshtokens_token_hash'), table_name='refreshtokens')
    op.drop_index(op.f('ix_refreshtokens_id'), table_name='refreshtokens')
    op.drop_index(op.f('ix_refreshtokens_expires_at'), table_name='refreshtokens')
    op.drop_table('refreshtokens')
    # ### end Alembic commands ###
