"""announcement_update

Revision ID: f102c9222eb8
Revises: f030eca78179
Create Date: 2025-08-23 05:22:21.946325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f102c9222eb8'
down_revision: Union[str, Sequence[str], None] = 'f030eca78179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcement', sa.Column('responsibilities', sa.String(), nullable=True))
    op.add_column('announcement', sa.Column('requirements', sa.String(), nullable=True))
    op.add_column('announcement', sa.Column('email', sa.String(), nullable=True))
    op.add_column('announcement', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('announcement', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcement', 'link')
    op.drop_column('announcement', 'phone')
    op.drop_column('announcement', 'email')
    op.drop_column('announcement', 'requirements')
    op.drop_column('announcement', 'responsibilities')
    # ### end Alembic commands ###
