"""course_model modif

Revision ID: f9492a127433
Revises: 3b4450aaddd3
Create Date: 2025-07-23 01:03:52.919094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9492a127433'
down_revision: Union[str, Sequence[str], None] = '3b4450aaddd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('course', sa.Column('course_type', sa.String(), nullable=True))
    op.add_column('course', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'expiry_date')
    op.drop_column('course', 'course_type')
    op.drop_column('course', 'image_url')
    # ### end Alembic commands ###
