"""DB Update

Revision ID: f9fb57bde513
Revises: 8b4f8e2d80d5
Create Date: 2025-08-30 12:54:44.909408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9fb57bde513'
down_revision: Union[str, Sequence[str], None] = '8b4f8e2d80d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('most_enrolled_course', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'metrics', 'course', ['most_enrolled_course'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'metrics', type_='foreignkey')
    op.drop_column('metrics', 'most_enrolled_course')
    # ### end Alembic commands ###
